name: Amaterasu
main: com.worldcretornica.amaterasu.Amaterasu
version: 1.1
description: >
             Allows a player to set on fire everything he is looking at.
commands:
    amaterasu:
        description: Sets ablaze what the player is looking at
        usage: amaterasu